#!/bin/sh

CONTRAB_BACKUP="/root/.scripts/._crontab.backup"

if [[ $(md5sum $CONTRAB_BACKUP | cut -d' ' -f1) == $(md5sum /etc/crontab | cut -d' ' -f1) ]]
then
    echo "File /etc/crontab has been modified !" | mail -s "[Security] Crontab changed" root
fi

echo "[OK] /etc/crontab stay unchanged !"
