#!/bin/sh

CONTRAB_BACKUP="/._contract.backup"

if [[ $(md5sum $CONTRAB_BACKUP | cut -d' ' -f1) == $(md5sum /etc/crontab | cut -d' ' -f1) ]]
then
    echo "Le fichier /etc/contrab a ete modifie !" | mail -s "[Security] Contrab changed" root
fi
